#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_TEMPLATE_DIR = ROOT / "templates" / "agent-template"
TARGET_TEMPLATES_DIR = ROOT / "templates"

# ── Validation constants (same as scaffold_module.py) ──────────────

NAME_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")
MAX_NAME_LENGTH = 64

BUSINESS_TERMS: set[str] = {
    "ecommerce", "e_commerce", "电商", "客服", "cs",
    "服装", "clothing", "fashion",
    "订单", "order", "售后", "refund", "return",
    "cad", "灯具", "lighting",
    "报价", "quote", "pricing",
    "自媒体", "social_media", "influencer",
}

SENSITIVE_NAMES: set[str] = {
    "env", ".env", "secret", "secrets",
    "key", "keys", "token", "tokens",
    "credential", "credentials", "password",
    "config", ".config",
}


# ── Helpers ─────────────────────────────────────────────────────────


def validate_name(name: str) -> list[str]:
    errors: list[str] = []
    if not name:
        errors.append("Agent name is required.")
        return errors
    if len(name) > MAX_NAME_LENGTH:
        errors.append(f"Agent name too long ({len(name)} > {MAX_NAME_LENGTH} chars).")
    if ".." in name or "/" in name or "\\" in name:
        errors.append(f"Path traversal detected in agent name: '{name}'")
    if not NAME_PATTERN.fullmatch(name):
        errors.append(
            f"Agent name must use snake_case (lowercase letters, digits, underscores), "
            f"starting with a letter. Got: '{name}'"
        )
    if name.startswith("."):
        errors.append(f"Agent name cannot start with '.': '{name}'")
    lower = name.lower()
    if lower in SENSITIVE_NAMES:
        errors.append(f"Agent name '{name}' is reserved and cannot be used.")
    if lower in BUSINESS_TERMS:
        errors.append(
            f"Agent name '{name}' contains a business term. "
            f"Agent names must be business-neutral."
        )
    return errors


def resolve_target_path(name: str) -> Path:
    try:
        target = (TARGET_TEMPLATES_DIR / name).resolve()
        resolved_base = TARGET_TEMPLATES_DIR.resolve()
    except (OSError, RuntimeError):
        target = TARGET_TEMPLATES_DIR.absolute() / name
        resolved_base = TARGET_TEMPLATES_DIR.absolute()
    try:
        target.relative_to(resolved_base)
    except ValueError:
        raise RuntimeError(
            f"Target path '{target}' is outside templates directory "
            f"'{resolved_base}'. Refusing to proceed."
        )
    return target


def load_source_agent_json() -> dict:
    """Load the reference agent.json as the source template."""
    src = SOURCE_TEMPLATE_DIR / "agent.json"
    return json.loads(src.read_text(encoding="utf-8"))


def render_agent_config(name: str) -> dict:
    """Create agent.json dict by patching the source template."""
    title = name.replace("_", " ").title()
    config = load_source_agent_json()

    config["id"] = name
    config["name"] = title
    config["description"] = (
        "Business-neutral agent template generated by Agent Harness Template. "
        "Customize id, name, provider, tools, and workflow for your use case."
    )
    config["metadata"] = {
        "author": "Agent Harness Template",
        "tags": ["business-neutral", "scaffold"],
        "purpose": "Developer reference example — not a business agent",
    }
    return config


def render_readme(name: str) -> str:
    title = name.replace("_", " ").title()
    return (
        f"# {title} Agent Template\n\n"
        f"This agent template was generated by the Agent Harness Template scaffold tool.\n\n"
        f"## Files\n\n"
        f"- `agent.json`: agent definition matching AgentConfig contract\n\n"
        f"## Usage\n\n"
        f"Ensure the API is running (`make dev-api`), then:\n\n"
        f"```bash\n"
        f"curl http://localhost:8005/api/agent-templates/{name} | python3 -m json.tool\n"
        f"```\n"
    )


def scaffold_agent(name: str, target_dir: Path, dry_run: bool = False) -> int:
    if dry_run:
        print(f"Generated files:")
        print(f"  templates/{name}/agent.json")
        print(f"  templates/{name}/README.md")
        print("\n[dry-run] No files were written.")
        return 0

    target_dir.mkdir(parents=True, exist_ok=True)

    agent_config = render_agent_config(name)
    readme = render_readme(name)

    (target_dir / "agent.json").write_text(
        json.dumps(agent_config, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    (target_dir / "README.md").write_text(readme, encoding="utf-8")

    print(f"Generated files:")
    print(f"  templates/{name}/agent.json")
    print(f"  templates/{name}/README.md")
    print(f"\nNext steps:")
    print(f"  - Review generated files: templates/{name}/")
    print(f"  - Run backend: make dev-api")
    print(f"  - Validate: curl http://localhost:8005/api/agent-templates/{name}")
    return 0


# ── CLI entry point ─────────────────────────────────────────────────


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Scaffold a new agent template.",
    )
    parser.add_argument(
        "--name", "-n", required=True,
        help="Agent name in snake_case (e.g. my_agent).",
    )
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be created without writing files.")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite existing target directory.")
    parser.add_argument("--preview", action="store_true",
                        help="Alias for --dry-run.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    name = args.name.strip()
    dry_run = args.dry_run or args.preview

    errors = validate_name(name)
    if errors:
        for err in errors:
            print(f"Error: {err}", file=sys.stderr)
        return 2

    try:
        target_dir = resolve_target_path(name)
    except RuntimeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    if target_dir.exists():
        if not args.force:
            print(
                f"Error: Agent already exists at {target_dir}. "
                f"Use --force to overwrite.",
                file=sys.stderr,
            )
            return 1
        shutil.rmtree(target_dir)

    return scaffold_agent(name, target_dir, dry_run=dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
