#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS_SCAFFOLDS_DIR = ROOT / "docs" / "scaffolds"

ALLOWED_KINDS = {"module", "agent", "eval", "generic"}

# ── Shared validation ──────────────────────────────────────────────

_script_dir = Path(__file__).resolve().parent
if str(_script_dir) not in sys.path:
    sys.path.insert(0, str(_script_dir))

from scaffold_validation import (  # noqa: E402
    validate_scaffold_name,
    resolve_safe_target,
)


def render_doc(name: str, kind: str) -> str:
    """Generate a neutral scaffold documentation markdown file."""
    title = name.replace("_", " ").title()

    lines = [
        f"# {title} — {kind.title()} Scaffold\n",
    ]

    # Purpose
    lines.append(f"Generated by Agent Harness Template scaffold tools.\n")
    lines.append(f"## Purpose\n")
    if kind == "module":
        lines.append(
            f"Business-neutral module scaffold for `{name}`. "
            f"Provides a starting point for a self-contained agent module.\n"
        )
    elif kind == "agent":
        lines.append(
            f"Business-neutral agent template for `{name}`. "
            f"Provides a starting point for an agent configuration.\n"
        )
    elif kind == "eval":
        lines.append(
            f"Business-neutral eval case for `{name}`. "
            f"Provides a starting point for trajectory evaluation.\n"
        )
    else:
        lines.append(f"Business-neutral scaffold documentation for `{name}`.\n")

    # Generated files
    lines.append(f"## Generated Files\n")
    if kind == "module":
        lines.append("- `modules/{name}/module.yaml`")
        lines.append("- `modules/{name}/agent.yaml`")
        lines.append("- `modules/{name}/services/{name}_service.py`")
        lines.append("- `modules/{name}/prompts/system.md`")
        lines.append("- `modules/{name}/skills/.gitkeep`")
        lines.append("- `modules/{name}/evals/.gitkeep`")
        lines.append("- `modules/{name}/README.md`")
    elif kind == "agent":
        lines.append("- `templates/{name}/agent.json`")
        lines.append("- `templates/{name}/README.md`")
    elif kind == "eval":
        lines.append("- `evals/cases/{name}.json`")
    else:
        lines.append("- (None — generic documentation)")
    lines.append("")

    # How to validate
    lines.append(f"## How to Validate\n")
    lines.append("- Review generated stubs for correctness.")
    lines.append("- Run: `make test-api`")
    lines.append("- Run: `python3 scripts/check_business_terms.py`")
    lines.append("")

    # How to run tests
    lines.append(f"## How to Run Tests\n")
    lines.append("```bash")
    lines.append("make test-api")
    lines.append("python3 scripts/run_evals.py")
    lines.append("python3 scripts/run_policy_evals.py")
    lines.append("```\n")

    # Next steps
    lines.append(f"## Next Steps\n")
    lines.append("- Review all generated stubs and customize as needed.")
    lines.append("- Add neutral tests for your scaffold.")
    lines.append("- Validate scaffold output with `python3 scripts/check_business_terms.py`.")
    lines.append("- Stage files: `git add <generated_paths>`")
    lines.append("- Domain-specific customisation belongs in a separate project, not in this template.\n")

    # Safety notes
    lines.append(f"## Safety Notes\n")
    lines.append("- This scaffold is business-neutral by default.")
    lines.append("- Do not add API keys, secrets, or credentials.")
    lines.append("- Do not add real provider configuration.")
    lines.append("- Do not add domain-specific business logic to template core.\n")

    return "\n".join(lines).format(name=name)


def scaffold_docs(name: str, kind: str, target_path: Path, dry_run: bool = False) -> int:
    if dry_run:
        print(f"Generated file:")
        print(f"  docs/scaffolds/{kind}-{name}.md")
        print("\n[dry-run] No files were written.")
        return 0

    target_path.parent.mkdir(parents=True, exist_ok=True)
    content = render_doc(name, kind)
    target_path.write_text(content, encoding="utf-8")

    print(f"Generated file:")
    print(f"  docs/scaffolds/{kind}-{name}.md")
    print(f"\nNext steps:")
    print(f"  - Review: docs/scaffolds/{kind}-{name}.md")
    print(f"  - Run: make test-api")
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Scaffold docs / README for generated modules, agents, or eval cases.",
    )
    parser.add_argument("--name", "-n", required=True,
                        help="Name in snake_case.")
    parser.add_argument("--kind", "-k", default="generic",
                        choices=sorted(ALLOWED_KINDS),
                        help="Kind of scaffold: module, agent, eval, or generic.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be created without writing files.")
    parser.add_argument("--force", action="store_true",
                        help="Overwrite existing target file.")
    parser.add_argument("--preview", action="store_true",
                        help="Alias for --dry-run.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    name = args.name.strip()
    kind = args.kind
    dry_run = args.dry_run or args.preview

    errors = validate_scaffold_name(name, kind="docs")
    if errors:
        for err in errors:
            print(f"Error: {err}", file=sys.stderr)
        return 2

    try:
        target_path = resolve_safe_target(DOCS_SCAFFOLDS_DIR, f"{kind}-{name}.md")
    except RuntimeError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2

    if target_path.exists():
        if not args.force:
            print(
                f"Error: Documentation already exists at {target_path}. "
                f"Use --force to overwrite.",
                file=sys.stderr,
            )
            return 1

    return scaffold_docs(name, kind, target_path, dry_run=dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
